#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$commonDev = [];
$commonDevConfigPath = __DIR__ . '/common/config/dev.php';
$consoleDev = [];
$consoleDevConfigPath = __DIR__ . '/console/config/dev.php';

if (file_exists($commonDevConfigPath)) {
    $commonDev = require($commonDevConfigPath);
}

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    $commonDev,
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php'),
    $consoleDev
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
